apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-cicd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/Sairam-K5/Jenkins-CI-CD-Project.git'
    targetRevision: HEAD
    path: k8s   # folder where django-deployment.yaml is kept

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
